global:
  scrape_interval: 5s
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 192.168.15.89:9090  
- job_name: aula
  static_configs:
  - targets:
    - 192.168.15.89:5000
- job_name: servidor_pessoal
  static_configs:
  - targets:
    - 192.168.15.89:9100